# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "catalyst"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["James R Swift"]
license = "Unlicense"
description = "Render CDXML ChemDraw files natively in Typst"
repository = "https://www.github.com/jamesrswift/catalyst"
keywords = ["ChemDraw", "CDXML", "Molecule"]
categories = []
disciplines = []
compiler = "0.12"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
